author: Anders Holmgren <andersmholmgren@gmail.com>
description: A library for manipulating [Dockerfile](https://docs.docker.com/reference/builder/)
homepage: https://github.com/Andersmholmgren/dockerfile
name: dockerfile
version: 0.0.2
dependencies: 
  quiver: '^0.21.3'
dependency_overrides: 
dev_dependencies: 
environment: 
  sdk: '>=1.8.0 <2.0.0'
