author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for manipulating [Dockerfile](https://docs.docker.com/reference/builder/)"
homepage: "https://github.com/Andersmholmgren/dockerfile"
name: "dockerfile"
version: "0.1.0"
dependencies:
  path: "^1.6.2"
  quiver: "^2.0.0+1"
environment: 
  sdk: ">=1.8.0 <3.0.0"
